local activity = require("modules.activity")

describe("activity.frame", function()
  it("advances eight frames per second", function()
    assert_eq(activity.frame(0.0), activity.SPINNER[1])
    assert_eq(activity.frame(0.125), activity.SPINNER[2])
    assert_eq(activity.frame(1.0), activity.SPINNER[1])
  end)

  it("returns the same frame for every pane at the same instant", function()
    assert_eq(activity.frame(7.3), activity.frame(7.3))
  end)
end)

describe("activity.format_duration", function()
  it("formats seconds", function() assert_eq(activity.format_duration(12), "12s") end)
  it("formats minutes and seconds", function() assert_eq(activity.format_duration(252), "4m12s") end)
  it("formats hours and minutes", function() assert_eq(activity.format_duration(3840), "1h04m") end)
end)

describe("activity.update", function()
  it("reports a shell as not busy", function()
    local store = activity.new_store()
    local result = activity.update(store, 1, "pwsh", 100, true)
    assert_eq(result.busy, false)
    assert_nil(result.notify)
  end)

  it("reports a build tool as busy with a spinner glyph", function()
    local store = activity.new_store()
    local result = activity.update(store, 1, "cargo", 100, true)
    assert_eq(result.busy, true)
    assert_eq(result.glyph, activity.frame(100))
  end)

  it("notifies when a long run finishes in an unfocused tab", function()
    local store = activity.new_store()
    activity.update(store, 1, "cargo", 100, false)
    local result = activity.update(store, 1, "pwsh", 100 + 252, false)
    assert_eq(result.busy, false)
    assert_eq(result.elapsed, 252)
    assert_true(result.notify ~= nil, "expected a notification")
    assert_eq(result.notify.body, "cargo — 4m12s")
  end)

  it("stays silent when the run was short", function()
    local store = activity.new_store()
    activity.update(store, 1, "cargo", 100, false)
    local result = activity.update(store, 1, "pwsh", 129, false)
    assert_nil(result.notify)
  end)

  it("stays silent when the tab is focused", function()
    local store = activity.new_store()
    activity.update(store, 1, "cargo", 100, true)
    local result = activity.update(store, 1, "pwsh", 400, true)
    assert_nil(result.notify)
  end)

  it("notifies once, not on every later tick", function()
    local store = activity.new_store()
    activity.update(store, 1, "cargo", 100, false)
    activity.update(store, 1, "pwsh", 400, false)
    local again = activity.update(store, 1, "pwsh", 401, false)
    assert_nil(again.notify)
  end)

  it("tracks panes independently", function()
    local store = activity.new_store()
    activity.update(store, 1, "cargo", 100, false)
    activity.update(store, 2, "pwsh", 100, false)
    local one = activity.update(store, 1, "pwsh", 400, false)
    local two = activity.update(store, 2, "pwsh", 400, false)
    assert_true(one.notify ~= nil, "pane 1 should notify")
    assert_nil(two.notify, "pane 2 was never busy")
  end)

  it("treats a missing process name as not busy", function()
    local store = activity.new_store()
    assert_eq(activity.update(store, 1, nil, 100, true).busy, false)
  end)
end)
