local agent = require("modules.agent")
local activity = require("modules.activity")
local glyph = require("glyph")

describe("agent.classify", function()
  it("trusts agent-deck when it reports a state", function()
    assert_eq(agent.classify("working", nil), "working")
    assert_eq(agent.classify("waiting", nil), "waiting")
    assert_eq(agent.classify("idle", nil), "idle")
  end)

  it("falls back to the process name for kiro and copilot", function()
    assert_eq(agent.classify(nil, "kiro"), "working")
    assert_eq(agent.classify(nil, "copilot"), "working")
  end)

  it("returns nil when no agent is present", function()
    assert_nil(agent.classify(nil, "pwsh"))
    assert_nil(agent.classify(nil, nil))
  end)
end)

describe("agent.pick", function()
  local function entries(map)
    return map
  end

  it("reads the active pane's agent", function()
    assert_eq(agent.pick(entries({ [3] = { status = "working" } }), 3), "working")
  end)

  it("prefers a pane that is waiting over the active one", function()
    local map = entries({ [1] = { status = "working" }, [7] = { status = "waiting" } })
    assert_eq(agent.pick(map, 1), "waiting")
  end)

  it("ignores panes agent-deck reports as inactive", function()
    local map = entries({ [1] = { status = "inactive" }, [2] = { status = "inactive" } })
    assert_nil(agent.pick(map, 1))
  end)

  it("survives an empty deck", function()
    assert_nil(agent.pick({}, 1))
    assert_nil(agent.pick(nil, 1))
  end)
end)

describe("agent.update", function()
  it("renders working in green with a spinner", function()
    local store = agent.new_store()
    local result = agent.update(store, "working", 10, true)
    assert_eq(result.segment.color, "#98BB6C")
    assert_true(result.segment.text:find(activity.frame(10), 1, true) ~= nil, "spinner missing")
  end)

  it("renders waiting in amber with a static glyph", function()
    local store = agent.new_store()
    local result = agent.update(store, "waiting", 10, true)
    assert_eq(result.segment.color, "#E6C384")
    local waiting = glyph.u(0x25D4)
    assert_true(#waiting > 0, "waiting glyph encoded to an empty string")
    assert_true(result.segment.text:find(waiting, 1, true) ~= nil, "waiting glyph missing")
  end)

  it("hides the segment when no agent is present", function()
    local store = agent.new_store()
    assert_nil(agent.update(store, nil, 10, true).segment)
  end)

  it("notifies on entering waiting, focused or not", function()
    local store = agent.new_store()
    agent.update(store, "working", 10, true)
    local result = agent.update(store, "waiting", 20, true)
    assert_true(result.notify ~= nil, "expected a waiting notification")
    assert_true(result.notify.body:find("input", 1, true) ~= nil, "body should mention input")
  end)

  it("notifies once per entry into waiting", function()
    local store = agent.new_store()
    agent.update(store, "waiting", 20, true)
    assert_nil(agent.update(store, "waiting", 21, true).notify)
  end)

  it("prefers the waiting notification over the finished one when unfocused", function()
    local store = agent.new_store()
    agent.update(store, "working", 10, false)
    local result = agent.update(store, "waiting", 20, false)
    assert_true(result.notify ~= nil, "expected a waiting notification")
    assert_true(result.notify.body:find("input", 1, true) ~= nil, "body should mention input, not finished")
  end)

  it("notifies with elapsed time when work finishes in an unfocused tab", function()
    local store = agent.new_store()
    agent.update(store, "working", 10, false)
    local result = agent.update(store, "idle", 10 + 252, false)
    assert_true(result.notify ~= nil, "expected a finished notification")
    assert_true(result.notify.body:find("4m12s", 1, true) ~= nil, "elapsed missing")
  end)

  it("stays silent when work finishes in the focused tab", function()
    local store = agent.new_store()
    agent.update(store, "working", 10, true)
    assert_nil(agent.update(store, "idle", 300, true).notify)
  end)
end)

describe("agent.on_user_var", function()
  it("overrides classification until the next idle", function()
    local store = agent.new_store()
    agent.on_user_var(store, "agent-state", "waiting")
    local result = agent.update(store, "working", 10, true)
    assert_eq(result.segment.color, "#E6C384")
  end)

  it("ignores unrelated variables", function()
    local store = agent.new_store()
    agent.on_user_var(store, "something-else", "waiting")
    assert_eq(agent.update(store, "working", 10, true).segment.color, "#98BB6C")
  end)
end)
