local platform = require("modules.platform")

describe("platform.detect", function()
  it("recognises windows", function()
    local p = platform.detect("x86_64-pc-windows-msvc")
    assert_eq(p.os, "windows")
    assert_eq(p.default_prog[1], "pwsh.exe")
    assert_eq(p.mod_primary, "CTRL|SHIFT")
  end)

  it("recognises macos and uses CMD", function()
    local p = platform.detect("aarch64-apple-darwin")
    assert_eq(p.os, "macos")
    assert_eq(p.mod_primary, "CMD")
  end)

  it("recognises linux", function()
    local p = platform.detect("x86_64-unknown-linux-gnu")
    assert_eq(p.os, "linux")
    assert_eq(p.mod_primary, "CTRL|SHIFT")
  end)

  it("points at the platform neovim config directory", function()
    assert_true(platform.detect("x86_64-pc-windows-msvc").nvim_config_dir:find("nvim", 1, true) ~= nil)
    assert_true(platform.detect("x86_64-unknown-linux-gnu").nvim_config_dir:find(".config", 1, true) ~= nil)
  end)
end)

describe("platform.shell_cmd", function()
  it("wraps a command for powershell on windows", function()
    local argv = platform.shell_cmd("windows", "git status")
    assert_eq(argv[1], "pwsh.exe")
    assert_eq(argv[2], "-NoProfile")
    assert_eq(argv[#argv], "git status")
  end)

  it("wraps a command for sh elsewhere", function()
    local argv = platform.shell_cmd("linux", "git status")
    assert_eq(argv[1], "sh")
    assert_eq(argv[2], "-c")
    assert_eq(argv[3], "git status")
  end)
end)
